swagger: "2.0"

info:
  title: "Sepsis Prediction API"
  version: "1.0"

basePath: /test/v1.0

paths:
  /prediction/:
    post:
      operationId: api.sepsis_predict_rf.predict  # ← This points to api/sepsis_predict_rf.py → def predict(body)
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              fv:
                type: string
      responses:
        '200':
          description: 'Returns sepsis prediction result'
          schema:
            $ref: '#/definitions/Prediction'

definitions:
  Prediction:
    type: object
    properties:
      prediction:
        type: string
