swagger: "2.0"

info:
  title: "Sepsis Prediction API"
  version: "1.0.0"

basePath: /test/v1.0

schemes:
  - http

consumes:
  - application/json
produces:
  - application/json

paths:
  /prediction/:
    post:
      summary: Predict sepsis
      operationId: api.prediction.class_instance.post
      description: Send patient feature data and receive a sepsis risk prediction
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              sepsis_fv:
                type: array
                items:
                  type: object
                  additionalProperties:
                    type: number
      responses:
        '200':
          description: Prediction result
          schema:
            type: object
            properties:
              sepsis_risk:
                type: array
                items:
                  type: number
        '500':
          description: Internal error

    get:
      summary: Health check
      operationId: api.prediction.class_instance.get
      responses:
        '200':
          description: Health status
